version: "3.5"
services:
  web-fe:
    build: .
    command: python app.py
    container_name: flask-app
    ports:
      - target: 5656
        published: 5657
    networks:
      - web-net
      - data-net
    volumes:
      - type: volume
        source: counter-vol
        target: /code
  redis:
    image: "redis:alpine"
    container_name: redis-app
    networks:
      data-net:

networks:
  web-net:
  data-net:
    internal: true

volumes:
  counter-vol: